[package]
name = "mark_downer"
version = "0.8.0"
authors = ["AndrewGrim <39337035+AndrewGrim@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "markdowner"
path = "src/lib.rs"

[[bin]]
name = "md"
path = "src/bin/md.rs"
