keywords1 = [
    "as",
    "break",
    "const",
    "continue",
    "crate",
    "else",
    "enum",
    "extern",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "return",
    "struct",
    "super",
    "trait",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
    "async",
    "await",
]
keywords2 = [
    "static",
    "dyn",
    "self",
    "Self",
    "Some",
    "None",
    "Ok",
    "Err",
    "mut",
    "pub",
    "ref",
    "false",
    "true",
    "bool",
    "usize",
]
single_line_comment = "//"
multi_line_comment_open = "/*"
multi_line_comment_close = "*/"